# Usamos la imagen oficial de WordPress que ya incluye PHP y Apache.
FROM wordpress:latest

# No se necesitan más pasos aquí, ya que montaremos el contenido
# (temas, plugins, etc.) usando volúmenes en docker-compose.yml.